name: RDP
on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
    - name: Configure Core RDP Settings By Yamzz
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0 -Force
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "SecurityLayer" -Value 0 -Force
        netsh advfirewall firewall delete rule name="RDP-Tailscale"
        netsh advfirewall firewall add rule name="RDP-Tailscale" dir=in action=allow protocol=TCP localport=3389
        Restart-Service -Name TermService -Force

    - name: Force Create User Aomsin Bypass GPO
      run: |
        # ใช้คำสั่งลัดระดับระบบปฏิบัติการเพื่อข้ามการตรวจสอบนโยบายรหัสผ่านความปลอดภัย (GPO Bypass)
        net user Aomsin 11 /add /y
        net localgroup Administrators Aomsin /add
        net localgroup "Remote Desktop Users" Aomsin /add
        wmic useraccount where name='Aomsin' set PasswordExpires=FALSE

    - name: Install Tailscale
      run: |
        $tsUrl = "https://tailscale.com"
        $installerPath = "$env:TEMP\tailscale.msi"
        Invoke-WebRequest -Uri $tsUrl -OutFile $installerPath
        Start-Process msiexec.exe -ArgumentList "/i", "`"$installerPath`"", "/quiet", "/norestart" -Wait
        Remove-Item $installerPath -Force

    - name: Establish Tailscale Connection
      run: |
        & "C:\Program Files\Tailscale\tailscale.exe" up --authkey ${{ secrets.TAILSCALE_AUTH_KEY }} --accept-routes

    - name: Keep Alive Loop (6 Hours)
      run: |
        Write-Host "RDP Setup Complete. Connecting to Tailscale..."
        $Seconds = 21600
        while ($Seconds -gt 0) {
            Write-Host "Remaining time: $Seconds seconds"
            Start-Sleep -Seconds 60
            $Seconds -= 60
        }
